{
    'data1': [
        "Ambush",
        "Animate Weapon",
        "Arctic Armour",
        "Artillery Ballista",
        "Barrage",
        "Bear Trap",
        "Blade Blast",
        "Blade Flurry",
        "Blade Trap",
        "Blade Vortex",
        "Bladefall",
        "Blast Rain",
        "Blink Arrow",
        "Blood Rage",
        "Burning Arrow",
        "Caustic Arrow",
        "Charged Dash",
        "Cobra Lash",
        "Cremation",
        "Cyclone",
        "Dash",
        "Desecrate",
        "Detonate Dead",
        "Double Strike",
        "Dual Strike",
        "Elemental Hit",
        "Ensnaring Arrow",
        "Ethereal Knives",
        "Explosive Arrow",
        "Explosive Concoction",
        "Explosive Trap",
        "Fire Trap",
        "Flamethrower Trap",
        "Flicker Strike",
        "Frenzy",
        "Frost Blades",
        "Galvanic Arrow",
        "Grace",
        "Haste",
        "Hatred",
        "Herald of Agony",
        "Herald of Ice",
        "Ice Shot",
        "Ice Trap",
        "Intuitive Link",
        "Lacerate",
        "Lancing Steel",
        "Lightning Arrow",
        "Lightning Strike",
        "Mirror Arrow",
        "Pestilent Strike",
        "Phase Run",
        "Plague Bearer",
        "Poacher's Mark",
        "Poisonous Concoction",
        "Precision",
        "Puncture",
        "Purity of Ice",
        "Rain of Arrows",
        "Reave",
        "Riposte",
        "Scourge Arrow",
        "Seismic Trap",
        "Shattering Steel",
        "Shrapnel Ballista",
        "Siege Ballista",
        "Smoke Mine",
        "Sniper's Mark",
        "Spectral Helix",
        "Spectral Shield Throw",
        "Spectral Throw",
        "Split Arrow",
        "Splitting Steel",
        "Storm Rain",
        "Summon Ice Golem",
        "Temporal Chains",
        "Temporal Rift",
        "Tornado",
        "Tornado Shot",
        "Toxic Rain",
        "Unearth",
        "Vaal Blade Vortex",
        "Vaal Burning Arrow",
        "Vaal Cyclone",
        "Vaal Detonate Dead",
        "Vaal Double Strike",
        "Vaal Grace",
        "Vaal Haste",
        "Vaal Impurity of Ice",
        "Vaal Lightning Strike",
        "Vaal Rain of Arrows",
        "Vaal Reave",
        "Vaal Spectral Throw",
        "Vampiric Link",
        "Venom Gyre",
        "Viper Strike",
        "Volatile Dead",
        "Whirling Blades",
        "Wild Strike",
        "Withering Step",
        "Absolution",
        "Ancestral Cry",
        "Ancestral Warchief",
        "Anger",
        "Animate Guardian",
        "Battlemage's Cry",
        "Berserk",
        "Bladestorm",
        "Blood and Sand",
        "Boneshatter",
        "Chain Hook",
        "Cleave",
        "Consecrated Path",
        "Corrupting Fever",
        "Decoy Totem",
        "Defiance Banner",
        "Determination",
        "Devouring Totem",
        "Dominating Blow",
        "Dread Banner",
        "Earthquake",
        "Earthshatter",
        "Enduring Cry",
        "Exsanguinate",
        "Flame Link",
        "Flesh and Stone",
        "General's Cry",
        "Glacial Hammer",
        "Ground Slam",
        "Heavy Strike",
        "Herald of Ash",
        "Herald of Purity",
        "Holy Flame Totem",
        "Ice Crash",
        "Immortal Call",
        "Infernal Blow",
        "Infernal Cry",
        "Intimidating Cry",
        "Leap Slam",
        "Molten Shell",
        "Molten Strike",
        "Perforate",
        "Petrified Blood",
        "Pride",
        "Protective Link",
        "Punishment",
        "Purity of Fire",
        "Rage Vortex",
        "Rallying Cry",
        "Reap",
        "Reckoning",
        "Rejuvenation Totem",
        "Searing Bond",
        "Seismic Cry",
        "Shield Charge",
        "Shield Crush",
        "Shockwave Totem",
        "Smite",
        "Static Strike",
        "Steelskin",
        "Summon Flame Golem",
        "Summon Stone Golem",
        "Sunder",
        "Sweep",
        "Tectonic Slam",
        "Vaal Ancestral Warchief",
        "Vaal Earthquake",
        "Vaal Glacial Hammer",
        "Vaal Ground Slam",
        "Vaal Impurity of Fire",
        "Vaal Molten Shell",
        "Vengeance",
        "Vigilant Strike",
        "Vitality",
        "Vulnerability",
        "War Banner",
        "Warlord's Mark",
        "Arc",
        "Arcane Cloak",
        "Arcanist Brand",
        "Armageddon Brand",
        "Assassin's Mark",
        "Ball Lightning",
        "Bane",
        "Blazing Salvo",
        "Blight",
        "Bodyswap",
        "Bone Offering",
        "Brand Recall",
        "Clarity",
        "Cold Snap",
        "Conductivity",
        "Contagion",
        "Conversion Trap",
        "Convocation",
        "Crackling Lance",
        "Creeping Frost",
        "Dark Pact",
        "Despair",
        "Destructive Link",
        "Discharge",
        "Discipline",
        "Divine Ire",
        "Elemental Weakness",
        "Energy Blade",
        "Enfeeble",
        "Essence Drain",
        "Eye of Winter",
        "Fireball",
        "Firestorm",
        "Flame Dash",
        "Flame Surge",
        "Flame Wall",
        "Flameblast",
        "Flammability",
        "Flesh Offering",
        "Forbidden Rite",
        "Freezing Pulse",
        "Frost Bomb",
        "Frost Shield",
        "Frost Wall",
        "Frostbite",
        "Frostblink",
        "Frostbolt",
        "Glacial Cascade",
        "Herald of Thunder",
        "Hexblast",
        "Hydrosphere",
        "Ice Nova",
        "Ice Spear",
        "Icicle Mine",
        "Incinerate",
        "Kinetic Blast",
        "Kinetic Bolt",
        "Lightning Spire Trap",
        "Lightning Tendrils",
        "Lightning Trap",
        "Lightning Warp",
        "Malevolence",
        "Manabond",
        "Orb of Storms",
        "Penance Brand",
        "Power Siphon",
        "Purifying Flame",
        "Purity of Elements",
        "Purity of Lightning",
        "Pyroclast Mine",
        "Raise Spectre",
        "Raise Zombie",
        "Righteous Fire",
        "Rolling Magma",
        "Scorching Ray",
        "Shock Nova",
        "Sigil of Power",
        "Siphoning Trap",
        "Soul Link",
        "Soulrend",
        "Spark",
        "Spellslinger",
        "Spirit Offering",
        "Storm Brand",
        "Storm Burst",
        "Storm Call",
        "Stormbind",
        "Stormblast Mine",
        "Summon Carrion Golem",
        "Summon Chaos Golem",
        "Summon Holy Relic",
        "Summon Lightning Golem",
        "Summon Raging Spirit",
        "Summon Reaper",
        "Summon Skeletons",
        "Summon Skitterbots",
        "Tempest Shield",
        "Vaal Arc",
        "Vaal Blight",
        "Vaal Clarity",
        "Vaal Cold Snap",
        "Vaal Discipline",
        "Vaal Fireball",
        "Vaal Flameblast",
        "Vaal Ice Nova",
        "Vaal Impurity of Lightning",
        "Vaal Lightning Trap",
        "Vaal Power Siphon",
        "Vaal Righteous Fire",
        "Vaal Spark",
        "Vaal Storm Call",
        "Vaal Summon Skeletons",
        "Void Sphere",
        "Voltaxic Burst",
        "Vortex",
        "Wave of Conviction",
        "Winter Orb",
        "Wintertide Brand",
        "Wither",
        "Wrath",
        "Zealotry",
        "Detonate Mines",
        "Portal",
        "Vaal Breach",
    ],
    'data2': [
        34,
        1,
        16,
        28,
        12,
        1,
        16,
        28,
        12,
        12,
        28,
        28,
        10,
        16,
        1,
        1,
        28,
        1,
        28,
        28,
        1,
        16,
        1,
        1,
        1,
        12,
        16,
        1,
        28,
        28,
        1,
        12,
        28,
        10,
        16,
        1,
        1,
        24,
        24,
        24,
        16,
        16,
        1,
        28,
        34,
        12,
        28,
        12,
        12,
        10,
        28,
        34,
        24,
        24,
        12,
        10,
        1,
        24,
        12,
        12,
        1,
        28,
        28,
        12,
        1,
        12,
        10,
        24,
        12,
        28,
        1,
        1,
        1,
        28,
        34,
        24,
        34,
        34,
        28,
        12,
        10,
        12,
        1,
        28,
        1,
        1,
        24,
        24,
        24,
        12,
        12,
        12,
        1,
        34,
        12,
        1,
        12,
        10,
        28,
        10,
        12,
        16,
        28,
        24,
        28,
        24,
        34,
        28,
        1,
        28,
        12,
        1,
        28,
        16,
        1,
        16,
        24,
        1,
        28,
        24,
        28,
        12,
        10,
        12,
        34,
        16,
        24,
        1,
        1,
        1,
        16,
        16,
        1,
        28,
        34,
        12,
        24,
        10,
        10,
        1,
        1,
        1,
        24,
        24,
        34,
        24,
        24,
        28,
        24,
        28,
        1,
        1,
        12,
        16,
        10,
        1,
        28,
        1,
        12,
        1,
        34,
        34,
        12,
        12,
        28,
        28,
        28,
        1,
        1,
        24,
        1,
        24,
        1,
        10,
        24,
        1,
        24,
        12,
        16,
        38,
        28,
        24,
        28,
        1,
        12,
        1,
        10,
        12,
        16,
        10,
        16,
        24,
        1,
        1,
        24,
        28,
        12,
        28,
        24,
        34,
        28,
        24
        28,
        24,
        24,
        24,
        12,
        28,
        1,
        28,
        10,
        12,
        1,
        28,
        24,
        12,
        16,
        1,
        1,
        34,
        1,
        24,
        1,
        1,
        28,
        16,
        28,
        34,
        12,
        12,
        12,
        12,
        28,
        1,
        28,
        1,
        12,
        10,
        24,
        12,
        1,
        28,
        12,
        1,
        24,
        24,
        28,
        28,
        1,
        16,
        1,
        12,
        28,
        34
        10,
        34,
        28,
        1,
        24,
        12,
        12,
        12,
        12,
        28,
        1,
        34,
        34,
        1,
        34,
        1,
        28,
        10,
        16,
        16,
        12,
        1,
        10,
        16,
        24,
        1,
        28,
        12,
        24,
        12,
        12,
        16,
        1,
        12,
        10,
        34,
        12,
        28,
        16,
        28,
        12,
        10,
        24,
        24,
        8,
        10,
        10,
    ]
}