# Generated by Django 4.0.4 on 2022-05-02 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gemplanner', '0002_quest_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestRewardMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(default='Scion', max_length=100)),
                ('achieve_type', models.CharField(default='reward', max_length=10)),
                ('gem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gemplanner.skillgem')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gemplanner.quest')),
            ],
        ),
    ]
